#vars
env_path: ~/.env
container_name: redmine
docker_image: redmine:latest   

#geerlingguy
pip_install_packages:
    - docker

docker_packages: 
    - "docker-ce"
docker_packages_state: present
docker_service_manage: false
docker_service_state: started
docker_service_enabled: true
docker_restart_handler_state: restarted

#Datadog 
datadog_site: datadoghq.eu
datadog_checks: 
    http_check:
        init_config:
        instances:
               - name: Redmine
                 url: http://0.0.0.0
                 timeout: 5
                 tags:
                   - app_redmine
                 collect_response_time: true
