
login:
	terraform login; 
init:	
	terraform init
	
validate:
	terraform validate	
	
plan:
	terraform plan
	
apply:
	terraform apply;
	
refresh:
	terraform refresh;	
	
output:
	terraform -output;	

create-config:
	bash apply_configuration.sh
	
destroy:
	terraform destroy
	
format_terraform:
	terraform fmt
